import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import MainProvider from '@/providers/MainProvider';

const inter = Inter({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <MainProvider>{children}</MainProvider>
    </html>
  );
}
