import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import MainProvider from '@/providers/MainProvider';
import Script from 'next/script';
import Head from 'next/head';

const inter = Inter({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <MainProvider>{children}</MainProvider>
        <Script
          id="scroll-restoration"
          dangerouslySetInnerHTML={{
            __html: `history.scrollRestoration = "manual";`,
          }}
        />
      </body>
    </html>
  );
}
