import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import MainProvider from '@/providers/MainProvider';
import Script from 'next/script';

const inter = Inter({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  charset: 'UTF-8',
  viewport:
    'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <MainProvider>{children}</MainProvider>
      <Script
        id="scrollRestoration"
        dangerouslySetInnerHTML={{
          __html: `history.scrollRestoration = "manual"; console.log(history.scrollRestoration);`,
        }}
      />
    </html>
  );
}
